Instructions and script to download and set all models
mozilla/translation-service pull request #14
Opened 2021-12-09 20:56 UTC by andrenatal

2021-12-09 23:32 UTC, eu9ene requested changes

2021-12-10 02:22 UTC, andrenatal commented on Makefile
> +	gunzip -r models/
🤷 ok. Whatever standard means here. We just need the job done

2021-12-10 02:41 UTC, eu9ene commented on Makefile
> +	gunzip -r models/
I mean whether it will work out of the box or a user will need to install some extra package

2021-12-10 02:43 UTC, eu9ene approved these changes

2021-12-10 02:44 UTC, merged